### ISSUE TITLE
bug: Reproducible Native App Crash when calling `FirebaseAuthentication.signOut()`

### ISSUE THREAD

**Issue by lincolnthree** [capawesome-team/capacitor-firebase#136]
**Plugin(s):**

Firebase Authentication 0.5.0

**Platform(s):**

Android

**Current behavior:**

Native Crash to Home Screen 

**Expected behavior:**

Plugin should throw an Error, not crash the Native app (IMO: plugins should *never* crash the entire app even if something is seriously wrong - unless there's about to be a nuclear security breach or something of that nature.)

**Steps to reproduce:**

Call `FirebaseAuthentication.signOut()` regardless of whether or not the user is not signed in via Firebase. This should be a No-Op, not a native crash.

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 44981614, pluginId: FirebaseAuthentication, methodName: signOut
V/Capacitor: callback: 44981614, pluginId: FirebaseAuthentication, methodName: signOut, methodData: {}
D/FirebaseAuth: Notifying id token listeners about a sign-out event.
D/FirebaseAuth: Notifying auth state listeners about a sign-out event.
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 44981615, pluginId: FirebaseAuthentication, methodName: signOut
V/Capacitor: callback: 44981615, pluginId: FirebaseAuthentication, methodName: signOut, methodData: {}
V/Capacitor/FirebaseAuthenticationPlugin: Notifying listeners for event authStateChange
V/Capacitor/Plugin: To native (Capacitor plugin): callbackId: 44981616, pluginId: FirebaseAuthentication, methodName: signOut
V/Capacitor: callback: 44981616, pluginId: FirebaseAuthentication, methodName: signOut, methodData: {}
```

```
E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
        at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
        at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
        at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.FacebookAuthProviderHandler.signOut(FacebookAuthProviderHandler.java:69)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.signOut(FirebaseAuthentication.java:272)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.signOut(FirebaseAuthenticationPlugin.java:197)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.maritlabs.topdecked.mtg, PID: 23622
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:607)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
        at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
        at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
        at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.FacebookAuthProviderHandler.signOut(FacebookAuthProviderHandler.java:69)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.signOut(FirebaseAuthentication.java:272)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.signOut(FirebaseAuthenticationPlugin.java:197)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121) 
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$com-getcapacitor-Bridge(Bridge.java:598) 
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Capacitor doctor:**

```
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌

```

**Comment by lincolnthree** [comment]
This apparently occurs if Facebook has been set up but failed to initialize (for example if the client token is missing.)

**Comment by robingenz** [comment]
You're right! 

Related to #25.

**Comment by yuvrajjsingh0** [comment]
Any update? I'm also facing the same issue

**Comment by yuvrajjsingh0** [comment]
Hey,

I have resolved this by doing following changes to AndroidManifest.xml file inside <application> tag:

```
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/fb_app_id"/>
<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/fb_client_token" />
```

Now, Facebook SDK will get initialized correctly and error will be resolved. Make sure you put Facbook App id and Facebook Client Token in your strings.xml file
