### ISSUE TITLE
bug: Facebook Authentication fails to initialize on Android

### ISSUE THREAD

**Issue by lincolnthree** [capawesome-team/capacitor-firebase#137]
**Plugin(s):**

Firebase Authentication 0.5.0

**Platform(s):**

Android

**Current behavior:**

Calling ` FirebaseAuthentication.signInWithFacebook({ customParameters: [] })` never returns from Promise. Native code never response to app;

**Expected behavior:**

The plugin call should either succeed or fail, but not hang indefinitely.

**Steps to reproduce:**

Apparently just call `await FirebaseAuthentication.signInWithFacebook({ customParameters: [] })`

**Related code:**

This used to work, but we updated to version 0.5.x and capacitor 3.6.x. and apparently it now does not.

```

    // Facebook SDK
    implementation 'com.facebook.android:facebook-android-sdk:13.1.0'

    // Firebase Version and Included Modules
    implementation platform('com.google.firebase:firebase-bom:29.3.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-iid'
```

Apparently the Facebook SDK is failing to init, though we have configured the token in AndroidManifest as specified:
```
I/FacebookInitProvider: Failed to auto initialize the Facebook SDK
    A valid Facebook app client token must be set in the AndroidManifest.xml or set by calling FacebookSdk.setClientToken before initializing the sdk.
        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.kt:440)
        at com.facebook.FacebookSdk.sdkInitialize(FacebookSdk.kt:393)
        at com.facebook.internal.FacebookInitProvider.onCreate(FacebookInitProvider.kt:21)
```

**Other information:**

**Capacitor doctor:**

```
$ npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by lincolnthree** [comment]
My fault. Apparently the client token was missing somehow even though I'm 99% sure we added it previously.
