### ISSUE TITLE
Error: `java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignIn`

### ISSUE THREAD

**Issue by vtolenti89** [capawesome-team/capacitor-firebase#152]
Hello,

We've been having some difficulties implementing this library in angular ionic project.
Upon its implementation, the app began to close automatically right after opening, and the only traces available are the one displayed in the android studio when debugging it:
 `
Process: com.XXX.mobile, PID: 26056
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignIn;
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.buildGoogleSignInClient(GoogleAuthProviderHandler.java:100)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.buildGoogleSignInClient(GoogleAuthProviderHandler.java:78)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.<init>(GoogleAuthProviderHandler.java:34)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:392)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:51)
        at dev.robingenz.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:38)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
`

Any ideas what is going on?
Is there any additional configuration to be made apart from configuring the `capacitor.config.ts` and creating a firebaseAuthentication Service?

Thanks

**Comment by robingenz** [comment]
Hi @vtolenti89,
Have you followed the [setup guide](https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/authentication/docs/setup-google.md) and added the following project variable to your `variables.gradle` file (usually `android/build.gradle`)?
```diff
ext {
+    rgcfaIncludeGoogle = true
}
```

**Comment by vtolenti89** [comment]
Hi @robingenz 
Thanks for your message. I just found time now to try it.
Even after configuring it according to the the setup guide, I am getting the following error on Android Studio:

`
Unable to load class 'com.android.build.api.variant.AndroidComponentsExtension'.
This is an unexpected error. Please file a bug containing the idea.log file.
`

**Comment by robingenz** [comment]
Okay, in this case I need a minimal, reproducible example so that I can debug the issue.

**Comment by vtolenti89** [comment]
It seems that there was some sort of conflict with this library and the following dependency:
`classpath 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.0'`

I dowgraded it to 1.3.0 and everything started to work.
It is still not clear why it was happening.

**Comment by robingenz** [comment]
Glad you found the problem. In that case I will close this issue.
Unfortunately, conflicts between dependencies can always occur. I try to keep the dependencies always up to date. Unfortunately I can't do much more.
Which plugin uses this dependency? Maybe I can find out more.
