### ISSUE TITLE
bug: App Close automatically and not opening I have used authentication plugin

### ISSUE THREAD

**Issue by zagham-nadeem** [capawesome-team/capacitor-firebase#180]
**Plugin(s):**

 @capacitor-firebase/authentication@1.0.0

**Platform(s):**

- Android Only

**Current behavior:**

- the app crashes right after launch. don't even see splash

**Related code:**

```
2022-08-18 15:27:23.567 16731-16731/com.thedarkeye.fitify E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thedarkeye.fitify, PID: 16731
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thedarkeye.fitify/com.thedarkeye.fitify.MainActivity}: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.thedarkeye.fitify. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3921)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4078)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8333)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.thedarkeye.fitify. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:184)
        at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@21.0.4:1)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:49)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:38)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:99)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:62)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:614)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:562)
        at com.getcapacitor.Bridge.<init>(Bridge.java:201)
        at com.getcapacitor.Bridge.<init>(Unknown Source:0)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1421)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:43)
        at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:37)
        at android.app.Activity.performCreate(Activity.java:8363)
        at android.app.Activity.performCreate(Activity.java:8341)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4078) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:233) 
        at android.os.Looper.loop(Looper.java:334) 
        at android.app.ActivityThread.main(ActivityThread.java:8333) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065) 
```

**Other information:**

**Capacitor doctor:**

```
 Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
  @capacitor/ios: 4.0.1

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.1
  @capacitor/android: 4.0.1
```

**Comment by robingenz** [comment]
This error occurs when the app is not configured correctly.
Make sure you have followed the [installation instructions](https://github.com/capawesome-team/capacitor-firebase/tree/main/packages/authentication#installation) carefully.
Did you add the `google-services.json` file?

**Comment by zagham-nadeem** [comment]
but i now i am getting this error 

`
2022-08-18 16:29:21.972 30170-30170/com.thedarkeye.fitify E/Capacitor/Console: File: http://localhost/vendor.js - Line 65929 - Msg: ERROR Error: Uncaught (in promise): Error: 10: 
    Error: 10: 
        at returnResult (http://localhost/:422:32)
        at win.androidBridge.onmessage (http://localhost/:397:21)
`

**Comment by robingenz** [comment]
You can fix it this way: https://stackoverflow.com/a/49450870/6731412

**Comment by zagham-nadeem** [comment]
not resolved same error occour

**Comment by robingenz** [comment]
Then have a look at this issue please: https://github.com/capawesome-team/capacitor-firebase/issues/51 

If it still won't work please provide a minimal, reproducible example so I can debug it.

**Comment by zagham-nadeem** [comment]
thanks it is solved
