### ISSUE TITLE
feat: improve error handling

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#25]
**Is your feature request related to a problem? Please describe:**

Error messages are currently poorly described and have no unique, uniform error codes.
This complicates cross-platform error handling.

**Describe the solution you'd like:**

The error messages should contain a helpful message and a unique code.

**Describe alternatives you've considered:**

No alternative solutions.

**Additional context:**

https://stackoverflow.com/questions/37859582/how-to-catch-a-firebase-auth-specific-exceptions

**Comment by george-martinec** [comment]
Any news ?

**Comment by robingenz** [comment]
Not yet. I plan to release this feature with Capacitor 5.

**Comment by ludonoel1** [comment]
Any news please ?
Someone knows when capacitor is going to be released ?

**Comment by george-martinec** [comment]
Any news ?

**Comment by ludonoel1** [comment]
Has someone tried to implement this lib: https://github.com/capacitor-community/facebook-login ?
Instead of waiting patch

**Comment by jakubforman** [comment]
Any news about issue?

**Comment by Sdqumar** [comment]
Hi @robingenz, thanks for the great work.
Does the above update cover signInWithFacebook?
if yes am still not getting a clear error message when using signInWithFacebook.


`/FirebaseAuthentication: signInWithCredential failed.
    com.google.firebase.auth.FirebaseAuthUserCollisionException: An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.
        at com.google.android.gms.internal.firebase-auth-api.zzxc.zzb(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzya.zza(com.google.firebase:firebase-auth@@21.1.0:7)
        at com.google.android.gms.internal.firebase-auth-api.zzyb.zzl(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzxy.zzq(com.google.firebase:firebase-auth@@21.1.0:3)
        at com.google.android.gms.internal.firebase-auth-api.zzxy.zze(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzxa.zze(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzvf.zzd(com.google.firebase:firebase-auth@@21.1.0:8)
        at com.google.android.gms.internal.firebase-auth-api.zzuy.zzb(com.google.firebase:firebase-auth@@21.1.0:3)
        at com.google.android.gms.internal.firebase-auth-api.zzyj.zzb(com.google.firebase:firebase-auth@@21.1.0:12)
        at com.google.android.gms.internal.firebase-auth-api.zzyj.zza(com.google.firebase:firebase-auth@@21.1.0:14)
        at com.google.android.gms.internal.firebase-auth-api.zzxp.zzq(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzvf.zzA(com.google.firebase:firebase-auth@@21.1.0:4)
        at com.google.android.gms.internal.firebase-auth-api.zzxb.zzu(com.google.firebase:firebase-auth@@21.1.0:5)
        at com.google.android.gms.internal.firebase-auth-api.zzwh.zzc(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzyc.run(com.google.firebase:firebase-auth@@21.1.0:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
D/Capacitor: Sending plugin error: {"save":false,"callbackId":"43697152","pluginId":"FirebaseAuthentication","methodName":"signInWithFacebook","success":false,"error":{"message":"signIn failed."}}`

**Comment by robingenz** [comment]
> Does the above update cover signInWithFacebook?

@Sdqumar Yes. Please create a new issue with a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can take a closer look.
