### ISSUE TITLE
bug:  required Firebase/AnalyticsWithoutAdIdSupport (= 10.2.0)

### ISSUE THREAD

**Issue by 24jr** [capawesome-team/capacitor-firebase#294]
upgrading several svelte things and vite  from month ago to latest including this from v1.2 to v 1.3

With npm run build and then npx cap sync I get issue 
```
CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport (from
        `../../../../node_modules/@capacitor-firebase/analytics`) was resolved to 1.3.0, which depends
        on
        Firebase/AnalyticsWithoutAdIdSupport (= 10.2.0)
``` 
What is it I am supposed to update? I think everything else is latest. I tried keeping 1.2 along with other updates but had issue still so figure I should roll with 1.3 and ask question
```
@capacitor-firebase/analytics@1.3.0
  ├── @capacitor/android@4.6.1
  ├── @capacitor/cli@4.6.1
  ├── @capacitor/core@4.6.1
  ├── @capacitor/device@4.1.0
  ├── @capacitor/filesystem@4.1.4
  ├── @capacitor/ios@4.6.1
  ├── @capacitor/local-notifications@4.1.4
  ├── @capacitor/share@4.1.0
  ├── @sentry/svelte@7.28.1
  ├── @sentry/tracing@7.28.1
  ├── @sveltejs/adapter-static@1.0.0-next.50
  ├── @sveltejs/kit@1.0.0-next.589
  ├── aws-amplify@4.3.45
  ├── chart.js@3.9.1
  ├── chartjs-adapter-moment@1.0.1
  ├── firebase@9.15.0
  ├── html-to-image@1.11.4
  ├── moment@2.29.4
  ├── pdfmake@0.3.0-beta.4
  ├── svelte@3.55.0
  ├── typescript@4.9.4
  └── vite@4.0.4
```
Isnt 9 the latest Firebase? Is that what it wants me to update to 10.2? If so how?

**Comment by robingenz** [comment]
Please paste the entire error message.

**Comment by 24jr** [comment]
```
npx cap sync
npm WARN ignoring workspace config at /Users/jrose/Documents/GitHub/livlyme-longhauler-tracker/packages/app/.npmrc 
✔ Copying web assets from build to android/app/src/main/assets/public in 88.75ms
✔ Creating capacitor.config.json in android/app/src/main/assets in 592.21μs
✔ copy android in 100.79ms
✔ Updating Android plugins in 1.71ms
[info] Found 5 Capacitor plugins for android:
       @capacitor-firebase/analytics@1.3.0
       @capacitor/device@4.1.0
       @capacitor/filesystem@4.1.4
       @capacitor/local-notifications@4.1.4
       @capacitor/share@4.1.0
✔ update android in 27.88ms
✔ Copying web assets from build to ios/App/App/public in 59.75ms
✔ Creating capacitor.config.json in ios/App/App in 200.33μs
✔ copy ios in 64.78ms
✔ Updating iOS plugins in 1.69ms
[info] Found 5 Capacitor plugins for ios:
       @capacitor-firebase/analytics@1.3.0
       @capacitor/device@4.1.0
       @capacitor/filesystem@4.1.4
       @capacitor/local-notifications@4.1.4
       @capacitor/share@4.1.0
✖ Updating iOS native dependencies with pod install - failed!
✖ update ios - failed!
[error] Analyzing dependencies
        [!] CocoaPods could not find compatible versions for pod
        "Firebase/AnalyticsWithoutAdIdSupport":
        In Podfile:
        CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport (from
        `../../../../node_modules/@capacitor-firebase/analytics`) was resolved to 1.3.0, which depends
        on
        Firebase/AnalyticsWithoutAdIdSupport (= 10.2.0)
        
        Firebase/AnalyticsWithoutAdIdSupport
        
        Specs satisfying the `Firebase/AnalyticsWithoutAdIdSupport,
        Firebase/AnalyticsWithoutAdIdSupport (= 10.2.0)` dependency were found, but they required a
        higher minimum deployment target.
        

```

**Comment by 24jr** [comment]
This is podfile. in a workspace so extra ../../
```
# require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorDevice', :path => '../../../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorLocalNotifications', :path => '../../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/@capacitor/share'
end

target 'App' do
  capacitor_pods
  # Add your Pods here 
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '../../../../node_modules/@capacitor-firebase/analytics'
end

# post_install do |installer|
#   assertDeploymentTarget(installer)
# end

```

**Comment by robingenz** [comment]
You need to update your local pods repo. Please run `pod install --repo-update` in the `ios/App/` directory.

**Comment by 24jr** [comment]
```
Last login: Tue Dec  6 13:23:45 on ttys003
jrose@j-rose app % cd ios/app
jrose@j-rose app % pod install --repo-update
Updating local specs repositories

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install --repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.6 (21G115)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseAnalytics', :path => '../../../../node_modules/@capacitor-firebase/analytics'
  pod 'CapacitorDevice', :path => '../../../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorLocalNotifications', :path => '../../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorShare', :path => '../../../../node_modules/@capacitor/share'
end

target 'App' do
  capacitor_pods
  # Add your Pods here 
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport', :path => '../../../../node_modules/@capacitor-firebase/analytics'
end

# post_install do |installer|
#   assertDeploymentTarget(installer)
# end
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/sources_manager.rb:140:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:237:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:236:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%28x86_64%29%2C+need+%28arm64e%29%29%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
jrose@j-rose app % 

```

**Comment by 24jr** [comment]
updating xcode now just in case has something to do with it

**Comment by robingenz** [comment]
Yes, please update to the latest XCode version and run the command again.

**Comment by 24jr** [comment]
ok updated xcode (that took a while) but got same error. If i remove pod file and run pos install i get
```
pod install              
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/AnalyticsWithoutAdIdSupport":
  In Podfile:
    CapacitorFirebaseAnalytics/AnalyticsWithoutAdIdSupport (from `../../../../node_modules/@capacitor-firebase/analytics`) was resolved to 1.3.0, which depends on
      Firebase/AnalyticsWithoutAdIdSupport (= 10.2.0)

    Firebase/AnalyticsWithoutAdIdSupport

Specs satisfying the `Firebase/AnalyticsWithoutAdIdSupport, Firebase/AnalyticsWithoutAdIdSupport (= 10.2.0)` dependency were found, but they required a higher minimum deployment target.
jrose@j-rose app % 

```

**Comment by 24jr** [comment]
maybe something with this https://stackoverflow.com/questions/36182969/cocoa-pods-error-with-pod-install

**Comment by robingenz** [comment]
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by 24jr** [comment]
Ah sounds difficult. Won't be doing that thanks for help going to either use diff package or not update everything else. Thanks anyway for help

**Comment by robingenz** [comment]
Okay, in this case i will close this issue.

**Comment by 24jr** [comment]
@robingenz I searched a bit more and this https://github.com/stripe/stripe-react-native/issues/1116 led me to `arch -x86_64 pod install --repo-update` which worked. I am on 2021 m1 macbook which I thought didnt need to run weird commands like that but idk that appears to have worked
<img width="719" alt="Screen Shot 2023-01-05 at 10 56 48 AM" src="https://user-images.githubusercontent.com/34662182/210824679-27d47239-0c6b-4292-9f68-5ea020dc9609.png">
