### ISSUE TITLE
bug: App crashes when plugin config is added in capacitor.config.ts

### ISSUE THREAD

**Issue by shubhamkashyapdev** [capawesome-team/capacitor-firebase#387]
### Plugin(s)

- [ ] Analytics
- [X] App
- [ ] App Check
- [ ] Authentication
- [X] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

App is crashing

### Expected behavior

App should work fine without crashing

### Reproduction

https://github.com/shubhamkashyapdev/ionic-vite-template/tree/capacitor-auth

### Steps to reproduce

install the npm package: @capacitor-firebase/authentication

Add the config from docs in capacitor.config.ts:
/// <reference types="@capacitor-firebase/authentication" />
import { CapacitorConfig } from "@capacitor/cli"

const config: CapacitorConfig = {
  appId: "com.employee.management.app",
  appName: "vite-and-capacitor",
  webDir: "dist",
  server: {
    androidScheme: "https",
  },
  plugins: {
    FirebaseAuthentication: {
      skipNativeAuth: false,
      providers: ["google.com"],
    },
  },
}

export default config

Start the application: npx cap open android

### Other information

Logs from android studio:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.employee.management.app, PID: 6842
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSignIn;
        at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.buildGoogleSignInClient(GoogleAuthProviderHandler.java:119)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.buildGoogleSignInClient(GoogleAuthProviderHandler.java:97)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.<init>(GoogleAuthProviderHandler.java:35)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:820)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:67)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:65)
        at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:105)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:644)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:600)
        at com.getcapacitor.Bridge.<init>(Bridge.java:213)
        at com.getcapacitor.Bridge.<init>(Unknown Source:0)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1519)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42)
        at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:8151)
        at android.app.Activity.performCreate(Activity.java:8135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3721)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3920)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:261)
        at android.app.ActivityThread.main(ActivityThread.java:8279)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.signin.GoogleSignIn" on path: DexPathList[[zip file "/data/app/~~HbQpFaKHYcgQNE4ctquwJA==/com.employee.management.app-PdEI8nDAls-kQzcrX_Q7wg==/base.apk"],nativeLibraryDirectories=[/data/app/~~HbQpFaKHYcgQNE4ctquwJA==/com.employee.management.app-PdEI8nDAls-kQzcrX_Q7wg==/lib/arm64, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.buildGoogleSignInClient(GoogleAuthProviderHandler.java:119) 
        at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.buildGoogleSignInClient(GoogleAuthProviderHandler.java:97) 
        at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.<init>(GoogleAuthProviderHandler.java:35) 
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.initAuthProviderHandlers(FirebaseAuthentication.java:820) 
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.<init>(FirebaseAuthentication.java:67) 
        at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.load(FirebaseAuthenticationPlugin.java:65) 
        at com.getcapacitor.PluginHandle.loadInstance(PluginHandle.java:115) 
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:105) 
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:65) 
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:644) 
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:600) 
        at com.getcapacitor.Bridge.<init>(Bridge.java:213) 
        at com.getcapacitor.Bridge.<init>(Unknown Source:0) 
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1519) 
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:42) 
        at com.getcapacitor.BridgeActivity.onCreate(BridgeActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:8151) 
        at android.app.Activity.performCreate(Activity.java:8135) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3721) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3920) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:261) 
        at android.app.ActivityThread.main(ActivityThread.java:8279) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 

### Capacitor doctor

$ npx cap doctor
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
   Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment]
This should be a duplicate of #384.

**Comment by shubhamkashyapdev** [comment]
I was missing this line: rgcfaIncludeGoogle = true
in android/variables.gradle, now the google auth is working.

**Comment by shubhamkashyapdev** [comment]
The auth is now working, closing the issue.
