### ISSUE TITLE
FATAL EXCEPTION: main - Attempt to invoke interface method 'com.getcapacitor.JSObject io.capawesome.capacitorjs.plugins.firebase.firestore.interfaces.Result.toJSObject()' on a null object reference

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/capacitor-firebase#469]
### Discussed in https://github.com/capawesome-team/capacitor-firebase/discussions/468

<div type='discussions-op-text'>

<sup>Originally posted by **FrancescoIoppolo** October 18, 2023</sup>
On Android I get this error:
Can you help me?

**FATAL EXCEPTION: main
                                                                                                    Process: digipetx.app, PID: 16119
                                                                                                    java.lang.NullPointerException: Attempt to invoke interface method 'com.getcapacitor.JSObject io.capawesome.capacitorjs.plugins.firebase.firestore.interfaces.Result.toJSObject()' on a null object reference
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.firestore.FirebaseFirestorePlugin$3.success(FirebaseFirestorePlugin.java:129)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.firestore.FirebaseFirestore.lambda$getDocument$4(FirebaseFirestore.java:84)
                                                                                                    	at io.capawesome.capacitorjs.plugins.firebase.firestore.FirebaseFirestore$$ExternalSyntheticLambda1.onSuccess(Unknown Source:4)
                                                                                                    	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:264)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8312)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)**</div>

**Comment by robingenz** [comment]
@FrancescoIoppolo I just published a dev version with a fix: 

```
npm i @capacitor-firebase/firestore@5.2.0-dev.e251415.1697621068
```

Can you please tell me if the problem is fixed?

**Comment by FrancescoIoppolo** [comment]
yes, solve it! great

now I get this: 

**FATAL EXCEPTION: CapacitorPlugins
                                                                                                     Process: digipetx.app, PID: 28035
                                                                                                     java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                     at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:783)
                                                                                                     at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                     at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                     at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                     at android.os.Looper.loop(Looper.java:264)
                                                                                                     at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                     at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:774)
                                                                                                     at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                     at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                     at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                     at android.os.Looper.loop(Looper.java:264)
                                                                                                     at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
                                                                                                     at com.google.android.gms.auth.api.signin.internal.zzi.zzd(Unknown Source:0)
                                                                                                     at com.google.android.gms.auth.api.signin.GoogleSignInClient.getSignInIntent(Unknown Source:34)
                                                                                                     at io.capawesome.capacitorjs.plugins.firebase.authentication.handlers.GoogleAuthProviderHandler.signIn(GoogleAuthProviderHandler.java:40)
                                                                                                     at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthentication.signInWithGoogle(FirebaseAuthentication.java:456)
                                                                                                     at io.capawesome.capacitorjs.plugins.firebase.authentication.FirebaseAuthenticationPlugin.signInWithGoogle(FirebaseAuthenticationPlugin.java:583)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                     at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:774)**

**Comment by robingenz** [comment]
This should help you: https://github.com/capawesome-team/capacitor-firebase/issues/456#issuecomment-1762671855
Please read the plugin documentation again and make sure you correctly configured the plugin.

**Comment by FrancescoIoppolo** [comment]
Yes you are right. Everything is OK! thanks

Il giorno mer 18 ott 2023 alle ore 11:45 Robin Genz <
***@***.***> ha scritto:

**Comment by robingenz** [comment]
Thanks for testing!
